# -*- coding: utf-8 -*-
"""152120201054_DeepLearning_HW1_Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qO7yFtGiGKCzCkc1mB7QnxXIZyWBCU3k
"""

import matplotlib.pyplot as plt

# Function to read file
def read_file(path):
    with open(path, "r", encoding="utf-8") as f:
        txt_file = f.read().lower()
    return txt_file

# Function to count words in a document
def count_words(document, selected_words):
    return [document.count(word) for word in selected_words]

# Function to generate bar chart
def generate_bar_chart(category_name, counts, selected_words):
    word_indexes = range(len(selected_words))
    plt.figure(figsize=(10, 2))
    plt.bar(word_indexes, counts, align='center', color='y' if category_name == 'spor' else 'r' if category_name == 'ekonomi' else 'g')
    plt.xlabel('Kelimeler')
    plt.ylabel('Tekrarlar')
    plt.title(category_name.capitalize())
    plt.xticks(word_indexes, selected_words, rotation='vertical')
    plt.show()

# Read selected words
with open('/content/secilenler.txt') as f:
    selected_words = f.read().splitlines()

# Read documents
txt_spor = read_file("/content/spor.txt")
txt_ekonomi = read_file("/content/ekonomi.txt")
txt_siyaset = read_file("/content/siyaset.txt")

# Count words for each category
spor_counts = count_words(txt_spor, selected_words)
ekonomi_counts = count_words(txt_ekonomi, selected_words)
siyaset_counts = count_words(txt_siyaset, selected_words)

# Generate bar charts for each category
generate_bar_chart('spor', spor_counts, selected_words)
generate_bar_chart('ekonomi', ekonomi_counts, selected_words)
generate_bar_chart('siyaset', siyaset_counts, selected_words)